---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-wordpress
  namespace: prod
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
