annotations:
  category: CMS
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.6-debian-12-r7
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r16
    - name: wordpress
      image: docker.io/bitnami/wordpress:6.1.0-debian-12-r18
  licenses: Apache-2.0
apiVersion: v2
appVersion: 6.4.3
dependencies:
- condition: memcached.enabled
  name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 6.x.x
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: WordPress 


name: wordpress

version: 0.1.0
