name: CD-CD
on:
  push:
    branches:
    - master
jobs:
  install-db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Connect to remote server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ip a
            cd ~/ansible
            ansible-playbook -i inv.yaml mysql.yaml -u root -e "user_db=${{ secrets.DB_USER }} pass_db=${{ secrets.DB_PASS }} name_${{ secrets.DB_NAME }}"

            
