name: CD-CD
on:
  push:
    branches:
    - master
jobs:
  install-db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Connect to remote server via SSH and copy themes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/ansible
            ansible-playbook -i inv.yaml mysql.yaml -u root -e "user_db=${{ secrets.DB_USER }} pass_db=${{ secrets.DB_PASS }} name_db=${{ secrets.DB_NAME }}"            
  
  ansible_notification:
    name: Ansible notification
    runs-on: ubuntu-latest
    needs: install-db
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "MySQL install and database created!"
        SLACK_TITLE: DB install status
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  helm-chart-generating:
    runs-on: ubuntu-latest
    needs: ansible_notification

    permissions:
      contents: write    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: xaos613/Project_HELM_REPO
 

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Process Helm chart
        run: |
          CHART_PATH="./wp-helm"
          
          sed -i 's/PRE Blog!/PROD Blog!/g' $CHART_PATH/values.yaml ;
          sed -i 's/pre_wp_base/wp_base/g' $CHART_PATH/values.yaml;
          sed -i 's/pre_wp_user/wp_user/g' $CHART_PATH/values.yaml;
          sed -i 's/pre-wordpress/prod-wordpress/g' $CHART_PATH/values.yaml;

      - name: Checking the chart with helm lint
        run: |          
          helm lint ./wp-helm
                  
      - name:  Create a directory and pack it
        run: |
          mkdir -p .helm-repo/
          helm package ./wp-helm -d .helm-repo

                    
      - name:  Generate index.yaml and commit
        run: |          
          if [ -f ".helm-repo/index.yaml" ]; then
            helm repo index .helm-repo --url ${HELM_REPO_URL} --merge .helm-repo/index.yaml
          else
            helm repo index .helm-repo --url ${HELM_REPO_URL}
          fi
                  
          helm repo index .helm-repo --url https://xaos613.github.io/Project_HELM_REPO/

          git config --local user.email "xaos613@gmail.com"
          git config --local user.name "Dmitry Sholomitski"
          git add .
          git commit -m "Add app "  || echo "No changes to commit"
          
        env:
          HELM_REPO_URL: https://xaos613.github.io/Project_HELM_REPO/

      
      - name: Push helm repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
        with:
          source-directory: .helm-repo/
          destination-github-username: xaos613
          destination-repository-name: Project_HELM_REPO
          user-email: xaos613@gmail.com
          target-branch: "master"    

  push_notification:
    name: Helm push_notification
    runs-on: ubuntu-latest
    needs: helm-chart-generating
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: "Helm package test and pushed!"
        SLACK_TITLE: Helm statusstatus
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
